defaults:
  - embs/essential_simple@_here_
  - trainer: deg_trainer
  - wandb_logger: default_logger
  - _self_

lr: 4.586815929703627e-05
n_attn_layers: 7
add_cell_line_to_tokens: true
d_model: 100
output_layers: 0
dropout: 0
n_attn_heads: 5
batch_size: 64
use_cell_line_autoencoder: false
use_layer_norm: true

wandb_logger:
  project: "essential-fusion"

fusion_model:
  _target_: model.fusion.FusionModel
  task:
    _target_: model.tasks.DEGClassificationTask
    target_key: "deg_label"
    input_dim: ${d_model}
    n_hidden_layers: ${output_layers}
    hidden_dim: 128
    output_dim: 6640  # number of genes
    dropout: ${dropout}
    use_gelu: true
    xavier_init: true
  learning_rate: ${lr}
  warmup_epochs: 5
  d_model: ${d_model}
  n_heads: ${n_attn_heads}
  n_layers: ${n_attn_layers}
  use_gate: false
  use_gelu: true
  xavier_init: true
  reconstruction_weight: 0
  dropout: ${dropout}
  contextualize_cell_line: true
  add_cell_line_to_tokens: ${add_cell_line_to_tokens}
  final_layer_cls: false

datamodule:
  _target_: data.datamodules.LeaderboardSplitDataModule
  dataset_type: "essential_deg"
  split_key: "pert_id"
  batch_size: ${batch_size}
  num_workers: 16
  validation_split_ratio: 0.2
  seed: 42
  fold: 0