model:
  C: 1e5
  balance_loss: true
emb_name: "random"
task_name: "expression/pert-prediction-essential-deg"

hydra:
  sweeper:
    max_batch_size: 20
    params:
      +fold_id: 0,1,2,3,4
      +cell_line: "'K-562','Jurkat','hTERT-RPE1','Hep-G2'"
      +estimator_name: "'no_change','prior','most_frequent'"